url: https://luke.monaghan.dev

# Site settings
title: Luke Monaghan
email: luke@monaghan.dev
description: "Hi, I'm Luke Monaghan. Software Developer specialising in Realtime Game Engines, XR (AR, VR), Shaders, "

social:
  - title: twitter
    url: https://twitter.com/LukePMonaghan
  - title: facebook
    url: https://www.facebook.com/lukepmonaghan
  - title: github
    url: https://github.com/lukemonaghan
  - title: instagram
    url: https://www.instagram.com/rangatangaa/

collections:
  employers:
    permalink: /:path/
  skills:
    permalink: /:path/
  history:
    permalink: /:path/

# Build settings
markdown: kramdown
permalink: pretty