url: https://luke.monaghan.dev

# Site settings
title: Luke Monaghan
email: luke@monaghan.dev
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/LukePMonaghan
  - title: facebook
    url: https://www.facebook.com/lukepmonaghan
  - title: github
    url: https://github.com/lukemonaghan


collections:
  employers:
    permalink: /:path/
  skills:
    permalink: /:path/

# Build settings
markdown: kramdown
permalink: pretty