# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 47b04b
  secondary: 70c574
  secondary-dark: 0f280f
  background: rgb(10, 10, 10, 1)
  backgroundlighter: rgb(15, 15, 15, 1)
  backgroundheader: rgb(20, 20, 20, 0.95)
  muted: 667766
  white: rgb(255, 255, 255, 1)
  black: rgb(10, 10, 10, 1)

# Font Families
font:
  primary: 'Montserrat, "Helvetica Neue",Helvetica,Arial,sans-serif'
  secondary: '"Droid Serif", "Helvetica Neue", Helvetica,Arial,sans-serif'

employment:
  heading: Employment
  description: Over my life i have worked at a range of places. Starting my first job doing computer repairs and services, slaving my way stacking shelves while studying. An internship, the indie thing for a while. Eventually putting my education to use developing server gameplay systems. Currently I am creating digital experiences for a wide range of clients some of which you can view in the portfolio.
